import { registerGWebComponent } from ".";
import { CircleShape } from "../shape/Circle";
import { EllipseShape } from "../shape/Ellipse";
import { HTMLShape } from "../shape/HTML";
import { ImageShape } from "../shape/Image";
import { LineShape } from "../shape/Line";
import { PathShape } from "../shape/Path";
import { PolylineShape } from "../shape/Polyline";
import { RectShape } from "../shape/Rect";
import { TextShape } from "../shape/Text";

registerGWebComponent('rect', RectShape);
registerGWebComponent('circle', CircleShape);
registerGWebComponent('text', TextShape);
registerGWebComponent('path', PathShape);
registerGWebComponent('ellipse', EllipseShape);
registerGWebComponent('image', ImageShape);
registerGWebComponent('line', LineShape);
registerGWebComponent('polyline', PolylineShape);
registerGWebComponent('html', HTMLShape);