module.exports = {
  Canvas: require('./src/canvas'),
  Group: require('./src/core/group'),
  Shape: require('./src/core/shape'),
  Rect: require('./src/shape/rect'),
  Circle: require('./src/shape/circle'),
  Ellipse: require('./src/shape/ellipse'),
  Path: require('./src/shape/path'),
  Text: require('./src/shape/text'),
  Line: require('./src/shape/line'),
  Image: require('./src/shape/image'),
  Polygon: require('./src/shape/polygon'),
  Polyline: require('./src/shape/polyline'),
  Arc: require('./src/shape/arc'),
  Fan: require('./src/shape/fan'),
  Cubic: require('./src/shape/cubic'),
  Quadratic: require('./src/shape/quadratic'),
  Marker: require('./src/shape/marker'),
  PathUtil: require('./src/util/path'),
  MatrixUtil: require('./src/util/matrix'),
  DomUtil: require('./src/util/dom'),
  Event: require('./src/event')
};
