import path from 'path';
import { fileURLToPath } from 'url';
import { defineConfig } from 'vite';
import glsl from 'vite-plugin-glsl';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  root: './__tests__/',
  server: {
    port: 8080,
    open: '/',
  },
  publicDir: 'static',
  plugins: [glsl()],
  resolve: {
    alias: {
      '@antv/g': path.resolve(__dirname, './packages/g/src'),
      '@antv/g-mobile-webgl': path.resolve(__dirname, './packages/g-mobile-webgl/src'),
      '@antv/g-plugin-matterjs': path.resolve(__dirname, './packages/g-plugin-matterjs/src'),
      '@antv/g-camera-api': path.resolve(__dirname, './packages/g-camera-api/src'),
      '@antv/g-pattern': path.resolve(__dirname, './packages/g-pattern/src'),
      '@antv/g-plugin-mobile-interaction': path.resolve(__dirname, './packages/g-plugin-mobile-interaction/src'),
      '@antv/g-canvas': path.resolve(__dirname, './packages/g-canvas/src'),
      '@antv/g-plugin-3d': path.resolve(__dirname, './packages/g-plugin-3d/src'),
      '@antv/g-plugin-physx': path.resolve(__dirname, './packages/g-plugin-physx/src'),
      '@antv/g-canvaskit': path.resolve(__dirname, './packages/g-canvaskit/src'),
      '@antv/g-plugin-a11y': path.resolve(__dirname, './packages/g-plugin-a11y/src'),
      '@antv/g-plugin-rough-canvas-renderer': path.resolve(__dirname, './packages/g-plugin-rough-canvas-renderer/src'),
      '@antv/g-components': path.resolve(__dirname, './packages/g-components/src'),
      '@antv/g-plugin-annotation': path.resolve(__dirname, './packages/g-plugin-annotation/src'),
      '@antv/g-plugin-rough-svg-renderer': path.resolve(__dirname, './packages/g-plugin-rough-svg-renderer/src'),
      '@antv/g-css-layout-api': path.resolve(__dirname, './packages/g-css-layout-api/src'),
      '@antv/g-plugin-box2d': path.resolve(__dirname, './packages/g-plugin-box2d/src'),
      '@antv/g-plugin-svg-picker': path.resolve(__dirname, './packages/g-plugin-svg-picker/src'),
      '@antv/g-css-typed-om-api': path.resolve(__dirname, './packages/g-css-typed-om-api/src'),
      '@antv/g-plugin-canvas-path-generator': path.resolve(__dirname, './packages/g-plugin-canvas-path-generator/src'),
      '@antv/g-plugin-svg-renderer': path.resolve(__dirname, './packages/g-plugin-svg-renderer/src'),
      '@antv/g-devtool': path.resolve(__dirname, './packages/g-devtool/src'),
      '@antv/g-plugin-canvas-picker': path.resolve(__dirname, './packages/g-plugin-canvas-picker/src'),
      '@antv/g-plugin-yoga': path.resolve(__dirname, './packages/g-plugin-yoga/src'),
      '@antv/g-dom-mutation-observer-api': path.resolve(__dirname, './packages/g-dom-mutation-observer-api/src'),
      '@antv/g-plugin-canvas-renderer': path.resolve(__dirname, './packages/g-plugin-canvas-renderer/src'),
      '@antv/g-plugin-zdog-canvas-renderer': path.resolve(__dirname, './packages/g-plugin-zdog-canvas-renderer/src'),
      '@antv/g-gesture': path.resolve(__dirname, './packages/g-gesture/src'),
      '@antv/g-plugin-canvaskit-renderer': path.resolve(__dirname, './packages/g-plugin-canvaskit-renderer/src'),
      '@antv/g-plugin-zdog-svg-renderer': path.resolve(__dirname, './packages/g-plugin-zdog-svg-renderer/src'),
      '@antv/g-image-exporter': path.resolve(__dirname, './packages/g-image-exporter/src'),
      '@antv/g-plugin-control': path.resolve(__dirname, './packages/g-plugin-control/src'),
      '@antv/g-shader-components': path.resolve(__dirname, './packages/g-shader-components/src'),
      '@antv/g-layout-blocklike': path.resolve(__dirname, './packages/g-layout-blocklike/src'),
      '@antv/g-plugin-css-select': path.resolve(__dirname, './packages/g-plugin-css-select/src'),
      '@antv/g-svg': path.resolve(__dirname, './packages/g-svg/src'),
      '@antv/g-lite': path.resolve(__dirname, './packages/g-lite/src'),
      '@antv/g-plugin-device-renderer': path.resolve(__dirname, './packages/g-plugin-device-renderer/src'),
      '@antv/g-web-animations-api': path.resolve(__dirname, './packages/g-web-animations-api/src'),
      '@antv/g-lottie-player': path.resolve(__dirname, './packages/g-lottie-player/src'),
      '@antv/g-plugin-dom-interaction': path.resolve(__dirname, './packages/g-plugin-dom-interaction/src'),
      '@antv/g-web-components': path.resolve(__dirname, './packages/g-web-components/src'),
      '@antv/g-math': path.resolve(__dirname, './packages/g-math/src'),
      '@antv/g-plugin-dragndrop': path.resolve(__dirname, './packages/g-plugin-dragndrop/src'),
      '@antv/g-webgl': path.resolve(__dirname, './packages/g-webgl/src'),
      '@antv/g-mobile-canvas': path.resolve(__dirname, './packages/g-mobile-canvas/src'),
      '@antv/g-plugin-gesture': path.resolve(__dirname, './packages/g-plugin-gesture/src'),
      '@antv/g-webgpu': path.resolve(__dirname, './packages/g-webgpu/src'),
      '@antv/g-mobile-canvas-element': path.resolve(__dirname, './packages/g-mobile-canvas-element/src'),
      '@antv/g-plugin-html-renderer': path.resolve(__dirname, './packages/g-plugin-html-renderer/src'),
      '@antv/react-g': path.resolve(__dirname, './packages/react-g/src'),
      '@antv/g-mobile-svg': path.resolve(__dirname, './packages/g-mobile-svg/src'),
      '@antv/g-plugin-image-loader': path.resolve(__dirname, './packages/g-plugin-image-loader/src'),
    },
  },
});
